#!/bin/bash
# Example commands for testing mesh communication

PORT="/dev/cu.usbserial-0001"  # Update with your port

echo "AntiHunter Mesh Testing Examples"
echo "================================"
echo ""
echo "1. Run all tests:"
echo "   ./test_mesh_commands.py $PORT --all"
echo ""
echo "2. Quick basic test:"
echo "   ./test_mesh_commands.py $PORT --basic"
echo ""
echo "3. Test message length limits (important!):"
echo "   ./test_mesh_commands.py $PORT --limits"
echo ""
echo "4. Test rate limiting:"
echo "   ./test_mesh_commands.py $PORT --rate"
echo ""
echo "5. Send a single command:"
echo "   ./test_mesh_commands.py $PORT --command 'STATUS'"
echo ""
echo "6. Monitor incoming messages for 30 seconds:"
echo "   ./test_mesh_commands.py $PORT --monitor 30"
echo ""
echo "7. Multiple specific tests:"
echo "   ./test_mesh_commands.py $PORT --basic --limits --rate"
echo ""
echo "Find your serial port:"
echo "  macOS:   ls /dev/cu.*"
echo "  Linux:   ls /dev/ttyUSB* /dev/ttyACM*"
echo "  Windows: Check Device Manager"
